---
title: "Sporophytic Tolerance PCA"
author: "Emma Chandler"
date: "September 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r}
library(dplyr)
library(devtools)
library(psych)
library(reshape)
library(tidyverse)
library(broom)
library(ggplot2)
library(ggforce)
library(ggfortify)
library(cluster)
library(PCAtools)

```

## Load data
```{r}
remove(list = ls())

data <- read.csv("~/Horsenettle/data/processed/correlation.csv", header = TRUE)


```

# Creating a figure theme for all plots
```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "serif"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```


## Correlations
```{r}
pairs.panels(data[,c(7:12)],
             gap = 0,
             bg = c("red", "blue")[data$location.x],
             pch=21)
```




## PCA of all sporophytic variables
```{r}
# Omitt all rows with nas
data.nona <- na.omit(data)

SPOR.PCA <- prcomp(data.nona[,c(7:12)], center = TRUE, scale. = TRUE)

summary(SPOR.PCA)
attributes(SPOR.PCA)
print(SPOR.PCA)


(PCA.p1 <- autoplot(prcomp(data.nona[,c(7:12)], center = TRUE, scale. = TRUE), 
         data = data.cold, colour = 'location', 
         loadings = TRUE, loadings.colour = 'black',
         loadings.label = TRUE, loadings.label.size = 4, loadings.label.colour = 'black', loadings.label.hjust = 1, loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#00BFFF", "#FF4040")) +
  scale_color_manual(values = c("#00BFFF", "#FF4040")) +
  xlim(-1,1) +
  ylim(-0.5,0.5) +
  HStheme())


(PCA.p2 <- autoplot(prcomp(data.nona[,c(7:12)], center = TRUE, scale. = TRUE), x=2, y=3, 
         data = data.cold, colour = 'location', 
         loadings = TRUE, loadings.colour = 'black',
         loadings.label = TRUE, loadings.label.size = 4, loadings.label.colour = 'black', loadings.label.hjust = 0, loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#00BFFF", "#FF4040")) +
  scale_color_manual(values = c("#00BFFF", "#FF4040")) +
  xlim(-1,1) +
  ylim(-0.5,0.5) +
  HStheme())


(PCA.p3 <- autoplot(prcomp(data.nona[,c(7:12)], center = TRUE, scale. = TRUE), x=1, y=3, 
         data = data.cold, colour = 'location', 
         loadings = TRUE, loadings.colour = 'black',
         loadings.label = TRUE, loadings.label.size = 4, loadings.label.colour = 'black', loadings.label.hjust = 0, loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#00BFFF", "#FF4040")) +
  scale_color_manual(values = c("#00BFFF", "#FF4040")) +
  xlim(-1,1) +
  ylim(-0.5,0.5) +
  HStheme())

# https://www.datacamp.com/community/tutorials/pca-analysis-r
```

## PCA Cold variables
```{r}

# Subset of cold variable data
data.cold <- data.nona[,c(2,3,8,10,11)]


# Cold PCA
cold.PCA <- data.cold %>% 
  dplyr::select(where(is.numeric)) %>% 
  scale() %>% 
  prcomp()

summary(cold.PCA)
print(cold.PCA)

# Graph PC1 and PC2
cold.PCA %>% 
  augment(data.cold) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC1,y = PC2, color = location)) +
  labs(title = "Cold PCA")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


centroids <- aggregate(cbind(x,y)~class,df,mean)
f         <- function(z)sd(z)/sqrt(length(z)) # function to calculate std.err
se        <- aggregate(cbind(se.x=x,se.y=y)~class,df,f)
centroids <- merge(centroids,se, by="class")    # add std.err column to centroids



```
## Plot PC1 values vs chlorophyll, CMS and photosynthesis
```{r}
# Graph PC1 and chlorophyll
cold.PCA %>% 
  augment(data.cold) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC1,y = CCHPL, color = location)) +
  labs(title = "Cold Chlorophyl vs PC1")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


# Graph PC1 and CMS
cold.PCA %>% 
  augment(data.cold) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC1,y = CCMS, color = location)) +
  labs(title = "Cold Chlorophyl vs PC1")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


# Graph PC1 and photosynthesis
cold.PCA %>% 
  augment(data.cold) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC2,y = CPS_dif, color = location)) +
  labs(title = "Cold Chlorophyl vs PC1")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


```



## PCA Hot variables
```{r}

# Subset of hot variable data
data.hot <- data.nona[,c(2,3,7,9,12)]

# Cold PCA
hot.PCA <- data.hot %>% 
  dplyr::select(where(is.numeric)) %>% 
  scale() %>% 
  prcomp()

summary(hot.PCA)
print(hot.PCA)

# Graph PC1 and PC2
hot.PCA %>% 
  augment(data.hot) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC1,y = PC2, color = location)) +
  labs(title = "Hot PCA")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()

autoplot(prcomp(data.hot[c(3:5)]), data = data.hot, colour = 'location', loadings = TRUE, loadings.colour = 'black',
         loadings.label = TRUE, loadings.label.size = 3)

```


## Plot PC1 values vs chlorophyll, CMS and photosynthesis

```{r}
# Graph PC1 and chlorophyll
hot.PCA %>% 
  augment(data.hot) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC2,y = HCHPL, color = location)) +
  labs(title = "Cold Chlorophyl vs PC2")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


# Graph PC1 and CMS
hot.PCA %>% 
  augment(data.hot) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC2,y = HCMS, color = location)) +
  labs(title = "Cold CMS vs PC2")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()


# Graph PC1 and photosynthesis
hot.PCA %>% 
  augment(data.hot) %>% 
  rename_at(vars(starts_with(".fitted")),
            list(~str_replace(.,".fitted",""))) %>% 
  ggplot(aes(x = PC1,y = HPS_dif, color = location)) +
  labs(title = "Hot PS vs PC1")+
  geom_point() +
  geom_mark_circle(aes(color = location)) +
  HStheme()

```
