---
title: "ALL ANOVA"
author: "Emma Chandler"
date: "September 21, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r}
library(dplyr)
library(devtools)
library(psych)

```

## Load data
```{r}
remove(list = ls())

H.CMS <- read.csv("~/Horsenettle/data/CMSdata.csv", header = TRUE)
C.CMS <- read.csv("~/Horsenettle/data/CMS_cold.csv", header = TRUE)
H.CHLP <- read.csv("~/Horsenettle/data/chlorophylldata.csv", header = TRUE)
C.CHLP <- read.csv("~/Horsenettle/data/chlorophyll_cold.csv", header = TRUE)

```

## Calculate tolerance variables- CMS, CHLP tolerance
```{r}
# Hot CMS
trtpro <- H.CMS$exp_trt / H.CMS$exp_max
cntrpro <- H.CMS$cntr_trt / H.CMS$cntr_max
# Calculate CMS using proportions
H.CMS$CMS <- ((1 - trtpro)/(1 - cntrpro))
# arcsin sqrt transformation because it is a proportion


# Hot CHLP
trtpro <- H.CHLP$treatment_final / H.CHLP$treatment_initial
cntrpro <- H.CHLP$control_final / H.CHLP$control_initial
# Calculate H.CHLP damage using proportions
H.CHLP$CHLP <- 1 - (cntrpro - trtpro)
# arcsine sqrt transformation for later t-test


# Cold CHLP
trtpro <- C.CHLP$treatment_final / C.CHLP$treatment_initial
cntrpro <- C.CHLP$control_final / C.CHLP$control_initial
# Calculate C.CHLP damage using proportions
C.CHLP$CHLP <- 1 - (cntrpro - trtpro)
# arcsine sqrt transformation for later t-test


# Cold CMS
trtpro <- C.CMS$exp_trt / C.CMS$exp_max
cntrpro <- C.CMS$cntr_trt / C.CMS$cntr_max
# Calculate CMS using proportions
C.CMS$CMS <- ((1 - trtpro)/(1 - cntrpro))
# arcsin sqrt transformation because it is a proportion

```
