---
title: "Sporophytic Tolerance PCA"
author: "Emma Chandler"
date: "September 12, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r message=FALSE}

library(dplyr)
library(ggfortify)
library(pca3d)
library(factoextra)

```

## Load data
```{r}
remove(list = ls())

data <- read.csv("~/Horsenettle/data/processed/correlationFull.csv", header = TRUE)


```

# Creating a figure theme for all plots
```{r message=FALSE}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```


## PCA of all sporophytic variables
```{r}
# Drop photosynthesis
data.noPS <- data %>% 
  select(1:14) %>% 
  na.omit()


# Omitt all rows with nas
data.nona <- na.omit(data)


ALL.PCA <- prcomp(data.noPS[,c(7:14)], center = TRUE, scale. = TRUE)

summary(ALL.PCA)
print(ALL.PCA)


(PCA.p1 <- autoplot(prcomp(data.noPS[,c(7:14)], center = TRUE, scale. = TRUE), 
         data = data.noPS, colour = 'population', 
         loadings = TRUE, 
         loadings.colour = 'black',
         loadings.label = TRUE, 
         loadings.label.size = 4, 
         loadings.label.colour = 'black', 
         loadings.label.hjust = 1, 
         loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  scale_color_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  # xlim(-0.8,0.8) +
  # ylim(-0.5,0.5) +
  HStheme())

# Saving graph
# ggsave("figures/PCA_full_1_pop.png", width = 7, height = 5, dpi = 300)

(PCA.p2 <- autoplot(prcomp(data.noPS[,c(7:14)], center = TRUE, scale. = TRUE), x=2, y=3, 
         data = data.noPS, colour = 'population', 
         loadings = TRUE, 
         loadings.colour = 'black',
         loadings.label = TRUE, 
         loadings.label.size = 4, 
         loadings.label.colour = 'black', 
         loadings.label.hjust = 0, 
         loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  scale_color_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  xlim(-0.5,0.5) +
  ylim(-0.5,0.5) +
  HStheme())

# Saving graph
# ggsave("figures/PCA_full_2_pop.png", width = 7, height = 5, dpi = 300)

(PCA.p3 <- autoplot(prcomp(data.noPS[,c(7:14)], center = TRUE, scale. = TRUE), x=1, y=3, 
         data = data.noPS, 
         colour = 'population', 
         loadings = TRUE, 
         loadings.colour = 'black',
         loadings.label = TRUE, 
         loadings.label.size = 4, 
         loadings.label.colour = 'black', 
         loadings.label.hjust = 0, 
         loadings.label.vjust = 0,
         frame = TRUE, frame.type = 't') +
  scale_fill_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  scale_color_manual(values = c("#009ACD", "#EE2C2C", "#00008B")) +
  xlim(-0.5,0.5) +
  ylim(-0.5,0.5) +
  HStheme())

# Saving graph
# ggsave("figures/PCA_full_3_pop.png", width = 7, height = 5, dpi = 300)

# https://www.datacamp.com/community/tutorials/pca-analysis-r
```


## 3D plot with first 3 principal componenets
```{r}
SPOR.PCA <- prcomp(data.noPS[,c(7:14)], center = TRUE, scale. = TRUE)
loca <- factor(data.noPS$location)

pca3d(SPOR.PCA, group = loca, 
      show.ellipses=TRUE, 
      ellipse.ci=0.75, 
      show.plane=FALSE, 
      palette = c("#00BFFF", "#FF4040"),)

# snapshotPCA3d(file="first_plot.png")
```


Get PCA individual data
```{r}
ID_PCA <- get_pca_ind(ALL.PCA)
head(ID_PCA$coord)

coor <- predict(ALL.PCA, newdata = data.noPS)

ALL <- cbind(data.noPS, coor)

# Data Visualization
(PC1 <- ggplot(ALL, aes(x = location, PC2, fill = location)) +     
    geom_boxplot(alpha = 0.8) +
    scale_fill_manual(values = c("#104E8B", "#B22222")) +
    labs(x = "Region", y = "PC3")+
    HStheme() +
    theme(legend.position = "none"))

# Saving graph
# ggsave("figures/SPOR_PC1.png", width = 7, height = 5, dpi = 300)

PC1.m <- aov(PC3 ~ location, data = ALL)
summary(PC1.m)
```









