---
title: "Pollen Tube Growth Rate Figures"
author: "Emma Chandler"
date: "3/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##########################################################################

# Pollen Tube Growth Rate Analysis and Figures
# Emma Chandler
# November 12, 2021

#############################################################################

```{r}
# Load Libraries
library(ggplot2)
library(rcompanion)
library(ggstatsplot)
library(dplyr)
library(tidyverse)
library(reshape2)


# Find working directory
# getwd()
# setwd("C:/Users/moin2/OneDrive/Documents/Horsenettle")

```

# Load Pollen Data --------------------------------------------------------

```{r message=FALSE}
# Remove everything from the environment
remove(list = ls())



# Load data
bilin <- read.csv("~/Horsenettle/data/processed/ptgrParams.csv", header = TRUE)
head(bilin)

germ_dat <- read.csv("~/Horsenettle/data/pollenTube_NEW.csv", header = TRUE)
head(germ_dat)
```


# Pollen Germination ------------------------------------------------------
```{r}
# Merge ID and Ramet
germ_dat <- mutate(germ_dat, ID = paste(ID, ramet)) # NEW

# Calculate pollen tube growth rate
germ_dat$PTGR <- germ_dat$mean_length / germ_dat$time

# Plot Data
gd <- germ_dat %>% 
  group_by(location, temp) %>% 
  summarise(PTGR = mean(PTGR))


ggplot(germ_dat, aes(x = temp, y = PTGR, color = location)) +
  geom_point() +
  geom_line(aes(group = ID)) +
  geom_line(data = gd, alpha = 1, size = 3) +
  theme_classic() +
  labs(x = expression(paste('Temperature (',~degree,'C)',sep='')), 
       y = "Mean Pollen Tube Growth Rate") +
  scale_colour_manual(values = c("#104E8B", "#B22222")) +
  theme(text = element_text(family = "sans"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank())

ggsave("figures/ptgr_mean.png", width = 7, height = 5, dpi = 300)

# http://derekogle.com/NCGraphing/resources/colors 

```


## Curve colored by population

```{r}
# Plot Data
gd <- germ_dat %>% 
  group_by(population, temp) %>% 
  summarise(PTGR = mean(PTGR))



ggplot(germ_dat, aes(x = temp, y = PTGR, color = population)) +
  geom_point() +
  geom_line(aes(group = ID)) +
  geom_line(data = gd, alpha = .8, size = 3) +
  theme_classic() +
  labs(x = expression(paste('Temperature (',~degree,'C)',sep='')), 
       y = "Percent Germination") +
  scale_colour_manual(values = c("#EE2C2C","#0000CD", "#8B1A1A", "#009ACD")) +
  theme(text = element_text(family = "sans"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank())

ggsave("figures/PTGR_mean_pop.png", width = 7, height = 5, dpi = 300)
```


## Reaction Norms for genets with atleast 3 ramets
```{r}
# Filtering genets with more than three ramets
germ_dat$iden <- str_extract(germ_dat$ID,"(\\w+)") 

rn_data <- germ_dat %>% 
  group_by(iden) %>% 
  filter(n() > 10)

# rn_data %>% 
#   filter(iden == "OP1") %>% 
ggplot(rn_data, aes(x = temp, y = PTGR, color = location)) +
  geom_point() +
  geom_line(aes(group = ID)) +
  facet_grid(cols = vars(iden)) +
  theme_classic() +
  labs(x = expression(paste('Temperature (',~degree,'C)',sep='')), 
       y = "Mean Pollen Tube Growth Rate") +
  scale_colour_manual(values = c("#104E8B", "#B22222")) +
  theme(text = element_text(family = "sans"), 
        axis.text.x = element_text(size = 10, angle = 90), 
        axis.text.y = element_text(size = 10),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank())

ggsave("figures/ptgr_rn.png", width = 7, height = 5, dpi = 300)

```

# Compare PTGR North and South at 30 degrees
```{r}

germ_dat %>% 
  filter(temp == 30) %>% 
  ggplot(aes(x= location, y = PTGR, fill = location))+
  geom_boxplot()+
  geom_jitter(width = 0.1)+
  theme_bw()+ 
  labs(x = "Location", 
       y = expression(paste('Temperature (',~degree,'C)',sep='')), 
       title = expression(paste('PTGR at 30',~degree,'C', sep=''))) +
  scale_color_manual(values = c("#104E8B", "#B22222")) +
  scale_fill_manual(values = c("#104E8B", "#B22222"))+
  theme(text = element_text(family = "serif"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank())

ggsave("figures/ptgr_30degree.png", width = 7, height = 5, dpi = 300)

```



# Bilinear Fit Data Analysis ----------------------------------------------
```{r}
# Data description
summary(bilin)



# T-test for minimum germination temperature
t.test(bilin$ctmin ~ bilin$location)

(Tmin <- ggplot(bilin, aes(location, ctmin, fill = location)) +
  geom_boxplot() +
  geom_jitter(width = 0.1)+
  theme_bw()+ 
  labs(x = "Location", 
       y = expression(paste('Temperature (',~degree,'C)',sep='')), 
       title = "Minimum PTGR Temperature") +
  scale_color_manual(values = c("dodgerblue", "red2")) +
  scale_fill_manual(values = c("dodgerblue", "red2"))+
  theme(text = element_text(family = "serif"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank()))


# T-test for maximum germination
t.test(bilin$ctmax ~ bilin$location)


(Tmax <- ggplot(bilin, aes(location, ctmax, fill = location)) +
  geom_boxplot() +
  geom_jitter(width = 0.1)+
  theme_bw()+ 
  labs(x = "Location", 
       y = expression(paste('Temperature (',~degree,'C)',sep='')), 
       title = "Maximum PTGR Temperature") +
  scale_color_manual(values = c("dodgerblue", "red2")) +
  scale_fill_manual(values = c("dodgerblue", "red2"))+
  theme(text = element_text(family = "serif"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank()))


# T-test for optimum germination
t.test(bilin$topt ~ bilin$location)

(Topt <- ggplot(bilin, aes(location, topt, fill = location)) +
  geom_boxplot() +
  geom_jitter(width = 0.1)+
  theme_bw()+ 
  labs(x = "Location", 
       y = expression(paste('Temperature (',~degree,'C)',sep='')), 
       title = "Optimum PTGR Temperature") +
  scale_color_manual(values = c("dodgerblue", "red2")) +
  scale_fill_manual(values = c("dodgerblue", "red2"))+
  theme(text = element_text(family = "serif"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank()))





# Code to stack graphs


bilin_plot <- melt(subset(bilin, select=c(location, ctmax, topt, ctmin)), id.var="location")


ggplot(bilin_plot, aes(x = location, y = value, fill = location)) + 
  geom_boxplot() +
  geom_jitter(width = 0.1)+
  facet_grid(variable ~ ., scales = "free_y") +
  theme_bw()+ 
  labs(x = "Location", 
       y = expression(paste('Temperature (',~degree,'C)',sep='')), 
       title = "Temperature Estimates from Quadratic Model") +
  scale_color_manual(values = c("#104E8B", "#B22222")) +
  scale_fill_manual(values = c("#104E8B", "#B22222"))+
  theme(text = element_text(family = "sans"), 
        axis.text.x = element_text(size = 12), 
        axis.text.y = element_text(size = 12),
        axis.title = element_text(size = 14),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        legend.text = element_text(size = 12),
        legend.title = element_blank())

ggsave("figures/ptgr_params.png", width = 7, height = 5, dpi = 300)

```

```{r message=FALSE}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "sans"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```


```{r warning=FALSE}

# Create column with ID only
bilin$iden <- str_extract(bilin$ID,"(\\w+)")

# Rename columns for graph
bilin_plot1 <- bilin %>% 
  rename(Tmax = ctmax, Tmin = ctmin, Topt = topt, Tolerance = thermal_tolerance, Breadth = breadth)

# Subset variables for facet grid ggplot
bilin_plot <- melt(subset(bilin_plot1, select=c(iden, location, Tmax, Topt, Tmin, Tolerance, Breadth)), id.var=c("iden", "location"))

ggplot(bilin_plot, aes(x = reorder(iden, value), y = value, color = location)) +
  geom_point()+
  geom_boxplot() +
  facet_grid(variable ~ ., scales = "free_y") +
  HStheme()+
  labs(title = "PTGR Curve Parameters", x = "Genotype", y = "Calculated Parameter") +
  scale_color_manual(values = c("#104E8B", "#B22222"))+
  theme(axis.text.x = element_text(angle = 90))
  

# ggsave("figures/PTGR_params2_DOT.png", width = 7, height = 5, dpi = 300)

# Same plot without tolerance and breadth
# Subset variables for facet grid ggplot
bilin_plot.1 <- melt(subset(bilin_plot1, select=c(iden, location, Tmax, Topt, Tmin)), id.var=c("iden", "location"))

ggplot(bilin_plot.1, aes(x = reorder(iden, value), y = value, color = location)) +
  geom_point()+
  geom_boxplot() +
  facet_grid(variable ~ ., scales = "free_y") +
  HStheme()+
  labs(title = "PTGR Curve Parameters", x = "Genotype", y = "Calculated Parameter") +
  scale_color_manual(values = c("#104E8B", "#B22222"))+
  theme(axis.text.x = element_text(angle = 90))
  

ggsave("figures/PTGR_params3_DOT.png", width = 7, height = 5, dpi = 300)
```

```{r}
# Is there a difference between Regions in Tmax
PGERM_max.R <- aov(ctmax ~ location, data = bilin)
summary(PGERM_max.R)

# Is there a difference between Regions in Topt
PGERM_opt.R <- aov(topt ~ location, data = bilin)
summary(PGERM_opt.R)

# Is there a difference between Regions in Tmin
PGERM_min.R <- aov(ctmin ~ location, data = bilin)
summary(PGERM_min.R)



# Is there a difference between Regions in Tmax
PGERM_max.ID <- aov(ctmax ~ ID, data = bilin)
summary(PGERM_max.ID)

# Is there a difference between Regions in Topt
PGERM_opt.ID <- aov(topt ~ ID, data = bilin)
summary(PGERM_opt.ID)

# Is there a difference between Regions in Tmin
PGERM_min.ID <- aov(ctmin ~ ID, data = bilin)
summary(PGERM_min.ID)


```



