---
title: "Sporophytic Tolerance Correlation"
author: "Emma Chandler"
date: "May 24, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries
```{r message=FALSE}
library(ggplot2)
library(plyr)
library(tidyverse)
library(ggcorrplot)
library(corrplot)
```

# Clear environment and set seed
```{r}
remove(list = ls())
set.seed(158358)
```


# Load data
```{r}
H.CMS <- read.csv("~/Horsenettle/data/processed/H.CMS.csv", header = TRUE)
C.CMS <- read.csv("~/Horsenettle/data/processed/C.CMS.csv", header = TRUE)
H.CHPL <- read.csv("~/Horsenettle/data/processed/H.CHPL.csv", header = TRUE)
C.CHPL <- read.csv("~/Horsenettle/data/processed/C.CHPL.csv", header = TRUE)
PS <- read.csv("~/Horsenettle/data/processed/PS.csv", header = TRUE)

```

### Rename column that are the same
```{r}
H.CMS$HCMS <- H.CMS$CMS
C.CMS$CCMS <- C.CMS$CMS
H.CHPL$HCHPL <- H.CHPL$CHPL
C.CHPL$CCHPL <- C.CHPL$CHPL

```


### Drop columns that won't be used
```{r}

H.CMS <- H.CMS[-c(1,6,8:13)]
C.CMS <- C.CMS[-c(1,6,8:13)]
H.CHPL <- H.CHPL[-c(1,6,8:13)]
C.CHPL <- C.CHPL[-c(1,6,8:13)]
PS <- PS[-c(1,6,8:12)]

```

### Check column types
```{r}
summary(PS)
summary(H.CMS)

C.CHPL$block <- as.character(C.CHPL$block)
H.CHPL$block <- as.character(H.CHPL$block)
C.CMS$block <- as.character(C.CMS$block)
H.CMS$block <- as.character(H.CMS$block)
PS$block <- as.character(PS$block)
```


# Create data frame with all tolerance variables
```{r}
CMS <- merge(H.CMS, C.CMS, by = c("ID", "location", "population", "number", "block"), all.x = FALSE, all = TRUE)
CHPL <- merge(H.CHPL, C.CHPL, by = c("ID", "location", "population", "number", "block"), all.x = FALSE, all = TRUE)
CC <- merge(CMS, CHPL, by = c("ID", "location", "population", "number", "block"), all.x = FALSE, all = TRUE)
ALL <- merge(CC, PS, by = c("ID", "location", "population", "number", "block"), all.x = TRUE, all = TRUE)

write.csv(x = ALL, file = "~/Horsenettle/data/processed/correlation.csv")

COR <- read.csv("~/Horsenettle/data/processed/correlation.csv", header = TRUE)

# Omit all except values of interest
COR <- COR[-c(1:6)]

```

Changing column names for ease of reading in correlation plot
```{r}
names(COR)[1] <- "Hot CMS"  
names (COR)[2] <- "Cold CMS"
names (COR)[3] <- "Hot CHPL"
names (COR)[4] <- "Cold CHPL"
names (COR)[5] <- "Cold PS"
names (COR)[6] <- "Hot PS"
```


# Create correlation matrix
```{r}
correlation <- cor(COR, use = "pairwise.complete.obs")

head(correlation[, 1:6])

p.mat <- cor_pmat(COR)
head(p.mat[, 1:4])

```

```{r}
HStheme <- function(){            
  theme_bw()+                          
  theme(axis.text.x = element_text(size = 12), 
        text = element_text(family = "serif"), 
        axis.text.y = element_text(size = 12),
        plot.subtitle = element_text(size = 16, vjust = 1, hjust = 0.5),
        axis.title = element_text(size = 14),
        panel.grid = element_blank(),
        plot.margin = unit(c(0.5, 0.5, 0.5, 0.5), units = , "cm"),
        plot.title = element_text(size = 20, vjust = 1, hjust = 0.5),
        legend.text = element_text(size = 12),
        legend.title = element_blank())
}
```



# Create correlation heat map
```{r}

ggcorrplot(correlation, hc.order = FALSE, outline.col = "white")

corrplot::corrplot(cor(correlation))

corrplot.mixed(correlation)

ggcorrplot(correlation, method = "circle", hc.order = TRUE)

```

